# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_setPara.ui'
#
# Created: Tue Oct 28 15:32:44 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(QtWidgets.QDialog):
    def setupUi(self, Dialog, para_program1, para_program2):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(546, 348)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox1 = QtGui.QGroupBox(Dialog)
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label1 = QtGui.QLabel(self.groupBox1)
        self.label1.setObjectName(_fromUtf8("label1"))
        self.gridLayout.addWidget(self.label1, 0, 0, 1, 1)
        self.lineEdit1 = QtGui.QLineEdit(self.groupBox1)
        self.lineEdit1.setObjectName(_fromUtf8("lineEdit1"))
        self.gridLayout.addWidget(self.lineEdit1, 0, 1, 1, 1)
        self.label2 = QtGui.QLabel(self.groupBox1)
        self.label2.setObjectName(_fromUtf8("label2"))
        self.gridLayout.addWidget(self.label2, 0, 2, 1, 1)
        self.lineEdit2 = QtGui.QLineEdit(self.groupBox1)
        self.lineEdit2.setObjectName(_fromUtf8("lineEdit2"))
        self.gridLayout.addWidget(self.lineEdit2, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.groupBox1)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.lineEdit3 = QtGui.QLineEdit(self.groupBox1)
        self.lineEdit3.setObjectName(_fromUtf8("lineEdit3"))
        self.gridLayout.addWidget(self.lineEdit3, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.lineEdit4 = QtGui.QLineEdit(self.groupBox1)
        self.lineEdit4.setObjectName(_fromUtf8("lineEdit4"))
        self.gridLayout.addWidget(self.lineEdit4, 1, 3, 1, 1)
        self.label3 = QtGui.QLabel(self.groupBox1)
        self.label3.setObjectName(_fromUtf8("label3"))
        self.gridLayout.addWidget(self.label3, 2, 0, 1, 1)
        self.lineEdit5 = QtGui.QLineEdit(self.groupBox1)
        self.lineEdit5.setObjectName(_fromUtf8("lineEdit5"))
        self.gridLayout.addWidget(self.lineEdit5, 2, 1, 1, 1)
        self.label4 = QtGui.QLabel(self.groupBox1)
        self.label4.setObjectName(_fromUtf8("label4"))
        self.gridLayout.addWidget(self.label4, 2, 2, 1, 1)
        self.lineEdit6 = QtGui.QLineEdit(self.groupBox1)
        self.lineEdit6.setObjectName(_fromUtf8("lineEdit6"))
        self.gridLayout.addWidget(self.lineEdit6, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label5 = QtGui.QLabel(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label5.sizePolicy().hasHeightForWidth())
        self.label5.setSizePolicy(sizePolicy)
        self.label5.setObjectName(_fromUtf8("label5"))
        self.horizontalLayout.addWidget(self.label5)
        self.spinBox1 = QtGui.QSpinBox(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox1.sizePolicy().hasHeightForWidth())
        self.spinBox1.setSizePolicy(sizePolicy)
        self.spinBox1.setObjectName(_fromUtf8("spinBox1"))
        self.horizontalLayout.addWidget(self.spinBox1)
        self.label6 = QtGui.QLabel(self.groupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label6.sizePolicy().hasHeightForWidth())
        self.label6.setSizePolicy(sizePolicy)
        self.label6.setObjectName(_fromUtf8("label6"))
        self.horizontalLayout.addWidget(self.label6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox1)
        self.groupBox2 = QtGui.QGroupBox(Dialog)
        self.groupBox2.setObjectName(_fromUtf8("groupBox2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label7 = QtGui.QLabel(self.groupBox2)
        self.label7.setObjectName(_fromUtf8("label7"))
        self.gridLayout_2.addWidget(self.label7, 0, 0, 1, 1)
        self.lineEdit7 = QtGui.QLineEdit(self.groupBox2)
        self.lineEdit7.setObjectName(_fromUtf8("lineEdit7"))
        self.gridLayout_2.addWidget(self.lineEdit7, 0, 1, 1, 1)
        self.label8 = QtGui.QLabel(self.groupBox2)
        self.label8.setObjectName(_fromUtf8("label8"))
        self.gridLayout_2.addWidget(self.label8, 0, 2, 1, 1)
        self.lineEdit8 = QtGui.QLineEdit(self.groupBox2)
        self.lineEdit8.setObjectName(_fromUtf8("lineEdit8"))
        self.gridLayout_2.addWidget(self.lineEdit8, 0, 3, 1, 1)
        self.label9 = QtGui.QLabel(self.groupBox2)
        self.label9.setObjectName(_fromUtf8("label9"))
        self.gridLayout_2.addWidget(self.label9, 1, 0, 1, 1)
        self.lineEdit9 = QtGui.QLineEdit(self.groupBox2)
        self.lineEdit9.setObjectName(_fromUtf8("lineEdit9"))
        self.gridLayout_2.addWidget(self.lineEdit9, 1, 1, 1, 1)
        self.label10 = QtGui.QLabel(self.groupBox2)
        self.label10.setObjectName(_fromUtf8("label10"))
        self.gridLayout_2.addWidget(self.label10, 1, 2, 1, 1)
        self.lineEdit10 = QtGui.QLineEdit(self.groupBox2)
        self.lineEdit10.setObjectName(_fromUtf8("lineEdit10"))
        self.gridLayout_2.addWidget(self.lineEdit10, 1, 3, 1, 1)
        self.label11 = QtGui.QLabel(self.groupBox2)
        self.label11.setObjectName(_fromUtf8("label11"))
        self.gridLayout_2.addWidget(self.label11, 2, 0, 1, 1)
        self.lineEdit11 = QtGui.QLineEdit(self.groupBox2)
        self.lineEdit11.setObjectName(_fromUtf8("lineEdit11"))
        self.gridLayout_2.addWidget(self.lineEdit11, 2, 1, 1, 1)
        self.label12 = QtGui.QLabel(self.groupBox2)
        self.label12.setObjectName(_fromUtf8("label12"))
        self.gridLayout_2.addWidget(self.label12, 2, 2, 1, 1)
        self.lineEdit12 = QtGui.QLineEdit(self.groupBox2)
        self.lineEdit12.setObjectName(_fromUtf8("lineEdit12"))
        self.gridLayout_2.addWidget(self.lineEdit12, 2, 3, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox2)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.lineEdit1.setText("%i"%para_program1[0])
        self.lineEdit2.setText("%.7f"%para_program1[1])
        self.lineEdit3.setText("%i"%para_program1[2])
        self.lineEdit4.setText("%i"%para_program1[3])        
        self.lineEdit5.setText("%i"%para_program1[4])
        self.lineEdit6.setText("%i"%para_program1[5])
        self.spinBox1.setValue(para_program1[6])
        
        self.lineEdit7.setText("%i"%para_program2[0])
        self.lineEdit8.setText("%.6f"%para_program2[1]) 
        self.lineEdit9.setText("%i"%para_program2[2])
        self.lineEdit10.setText("%i"%para_program2[3])
        self.lineEdit11.setText("%i"%para_program2[4])
        self.lineEdit12.setText("%.3f"%para_program2[5]) 
        
        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox1.setTitle(_translate("Dialog", "DAQ参数设置", None))
        self.label1.setText(_translate("Dialog", "方差长度设置", None))
        self.label2.setText(_translate("Dialog", "过滤阈值设置", None))
        self.label.setText(_translate("Dialog", "平滑数据长度", None))
        self.label_2.setText(_translate("Dialog", "平滑次数设置", None))
        self.label3.setText(_translate("Dialog", "峰谷判决步长", None))
        self.label4.setText(_translate("Dialog", "相位变化步长", None))
        self.label5.setText(_translate("Dialog", "拟合类型", None))
        self.label6.setText(_translate("Dialog", "说明：0代表默认的多项式拟合", None))
        self.groupBox2.setTitle(_translate("Dialog", "Spectra Suite参数设置", None))
        self.label7.setText(_translate("Dialog", "方差长度设置", None))
        self.label8.setText(_translate("Dialog", "过滤阈值设置", None))
        self.label9.setText(_translate("Dialog", "平滑数据长度", None))
        self.label10.setText(_translate("Dialog", "平滑次数设置", None))
        self.label11.setText(_translate("Dialog", "峰谷判决步长", None))
        self.label12.setText(_translate("Dialog", "峰谷过滤阈值", None))

